### ISSUE TITLE
[1] Test new workaround for Exoscale EIP issue

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-kubespray#60] opened 2021-03-02 16:26 UTC
**Describe the bug**

When a worker is added to an Exoscale EIP, then it cannot see itself via said EIP. There is currently [a workaround for that](https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/exoscale/modules/kubernetes-cluster/templates/cloud-init.tmpl#L37) in Kubespray. However, the workaround is "lost" when worker nodes are restarted.

To this end, I came up with a [new way to fix the EIP issue](https://github.com/kubernetes-sigs/kubespray/pull/7337), by assigning the EIP to a loopback interface.

Just to make sure, please test if the new fix works and approve the upstream Kubespray PR.

**To Reproduce**
Steps to reproduce the "bad" behavior:

0. Check out `compliantkubernetes-kubespray` (e.g., 02c97ba8db31f2fe8e50a212b66e11f49685c48a)
1. Create a new [Compliant Kubernetes service cluster on Exoscale](https://compliantkubernetes.io/operator-manual/exoscale/)
2. Make an Ingress request: `curl $EIP`. You should get the response `default backend - 404`,
3. Reboot the worker nodes: `ansible -i ./inventory/cksc/inventory.ini -m reboot kube-node`
4. Make a new Ingress request: `curl $EIP`. You will get a timeout.
5. Nuke the cluster.

To test the "good" version:

0. Check out the fixed version of Kubespray:
  ```
  cd kubespray
  git remote add ck git@github.com:cristiklein/kubespray
  git fetch ck
  git checkout fix-eip-issue
  ```
Perform steps 1-5 above.
  

**Expected behavior**

`curl $EIP` should return a 404.

**Screenshots**

**Version (add all relevant versions):**

- Compliant Kubernetes apps version [e.g. v0.11.0]
- Compliant Kubernetes Kubespray (02c97ba8db31f2fe8e50a212b66e11f49685c48a)
- Kubespray [bdd36c2d3465a98c2e7e95fb9080b7fa1a08edfa](https://github.com/kubernetes-sigs/kubespray/commit/bdd36c2d3465a98c2e7e95fb9080b7fa1a08edfa)

**Comment by cristiklein** [comment] 2021-03-04 09:49
Seems like this problem is extremely rare and nobody except me bumped into it. We leave this for now and pick it up again if anyone gets bitten anew. Until then, here is the [upstream Kubespray PR](https://github.com/kubernetes-sigs/kubespray/pull/7337) with an alternative solution.

**Comment by cristiklein** [comment] 2021-03-31 16:14
I'm not sure to understand what you mean. For testing this, I argued to
nuke the bad cluster in step 5 and redeploy from scratch. Feels to me that
this is the cleanest way to check that the fix will work for all future
setups.

**Comment by simonklb** [comment] 2021-04-01 14:36
My bad, I jumped the gun here. AFAICT deploying from scratch works as intended, managed a full deployment and everything looks green. I'm just curious if we need to handle existing deployments?

**Comment by cristiklein** [comment] 2021-04-06 09:27
To my knowledge, we don't need to handle existing deployments, since we currently have no production deployments on Exoscale.

Would you mind adding some comments upstream, so we can close the issue?

**Comment by simonklb** [comment] 2021-04-06 12:42
Closing this as it's been tested on our side. Feel free to re-open if you think it should stay open until it's decided on upstream.

**Closed by simonklb** 2021-04-06 12:42 UTC
Labels: bug, good first issue, quick issue
