### ISSUE TITLE
Rook Ceph OSD crashing 

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-kubespray#130] opened 2021-10-26 15:07 UTC
**Describe the bug**

After a fresh install of ck8s on exoscale. One of the osd pods went into a crashloop. 

**To Reproduce**
Try to create a cluster on exoscale, you should be able to see such an error. But, we are not always sure that such errors appear. 

**Expected behavior**
Osd needs to not be in crash loop. 

**Screenshots**

```bash 
debug 2021-10-25T13:06:31.326+0000 7f715038ef40 -1 bluefs _check_new_allocations invalid extent 1: 0x6d2d70000~400000: wasn't given but allocated for ino 1
debug 2021-10-25T13:06:31.326+0000 7f715038ef40 -1 bluefs mount failed to replay log: (14) Bad address
debug 2021-10-25T13:06:31.326+0000 7f715038ef40 -1 bluestore(/var/lib/ceph/osd/ceph-1) _open_bluefs failed bluefs mount: (14) Bad address
debug 2021-10-25T13:06:31.326+0000 7f715038ef40  1 bdev(0x55683bf47180 /var/lib/ceph/osd/ceph-1/block) close
debug 2021-10-25T13:06:31.646+0000 7f715038ef40 -1 osd.1 0 OSD:init: unable to mount object store
debug 2021-10-25T13:06:31.646+0000 7f715038ef40 -1  ** ERROR: osd init failed: (14) Bad address
```

```bash
debug 2021-10-26T14:43:11.496+0000 7f2dee5f2700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
debug 2021-10-26T14:43:11.500+0000 7f2deedf3700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
debug 2021-10-26T14:43:11.500+0000 7f2def5f4700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
failed to fetch mon config (--no-mon-config to skip)
```

**Version (add all relevant versions):**
v 1.17.0

**Comment by tordsson** [comment] 2021-11-11 10:07
Duplicate of https://github.com/elastisys/compliantkubernetes-kubespray/issues/121 ?

**Closed** 2022-07-07 12:03 UTC
Labels: bug
