### ISSUE TITLE
Thoughts on adding support for Azure ?

### ISSUE THREAD

**Issue by anwarchk** [elastisys/compliantkubernetes-kubespray#312] opened 2023-09-05 23:20 UTC
**Is your feature request related to a problem? Please describe.**
Currently the option to init doesn't accept `azure` as a value. Are there plans to support Azure ?

**Describe the solution you'd like**
Just like GCP and AWS, Azure is supported as a cloud provider value to init.

**Comment by cristiklein** [comment] 2023-09-08 11:48
Duplicate of https://github.com/elastisys/compliantkubernetes/issues/666 

Closing.

**Closed by cristiklein** 2023-09-08 11:48 UTC
Labels: feature
